### ISSUE TITLE
$ reference not found

### ISSUE THREAD

**Issue by aliakhtar** [mityalebedev/The-Shell#18]
Hey, fantastic theme!

I'm seeing the error `shell.js?v=512d706020:1 Uncaught ReferenceError: $ is not defined
    at shell.js?v=512d706020:1` in the console when I load my site which is using shell.

It refers to this line: https://github.com/mityalebedev/The-Shell/blob/master/assets/js/shell.js#L2

Perhaps some required dependency is missing?

**Comment by mityalebedev** [comment]
Thanks @aliakhtar, it's outdated code and it's fixed in the [2.0.0 release](https://github.com/mityalebedev/The-Shell/releases/tag/v2.0.0) and here https://github.com/mityalebedev/The-Shell/pull/17
