### ISSUE TITLE
Problem when upload on wordpress

### ISSUE THREAD

**Issue by hsayed21** [mityalebedev/The-Shell#35]
hi there,

How i can use it with wordpress ?

When i upload in wordpress occure error

**This Error Message:**

Installing theme from uploaded file: the-shell.zip
Unpacking the package…

Installing the theme…

The package could not be installed. The theme is missing the style.css stylesheet.

Theme installation failed.

**Comment by mityalebedev** [comment]
This one is not a wordpress theme, it's for the https://ghost.org/
